export const landscapesImages = [
    'src/assets/images/gallery/landscapes/landscapes_01.jpg',
    'src/assets/images/gallery/landscapes/landscapes_02.jpg',
    'src/assets/images/gallery/landscapes/landscapes_03.jpg',
    'src/assets/images/gallery/landscapes/landscapes_04.jpg',
    'src/assets/images/gallery/landscapes/landscapes_05.jpg',
    'src/assets/images/gallery/landscapes/landscapes_06.jpg',
    'src/assets/images/gallery/landscapes/landscapes_07.jpg',
    'src/assets/images/gallery/landscapes/landscapes_08.jpg',
    'src/assets/images/gallery/landscapes/landscapes_09.jpg',
    'src/assets/images/gallery/landscapes/landscapes_10.jpg',
    'src/assets/images/gallery/landscapes/landscapes_11.jpg',
    'src/assets/images/gallery/landscapes/landscapes_12.jpg',
    'src/assets/images/gallery/landscapes/landscapes_13.jpg',
    'src/assets/images/gallery/landscapes/landscapes_14.jpg',
    'src/assets/images/gallery/landscapes/landscapes_15.jpg',
    'src/assets/images/gallery/landscapes/landscapes_16.jpg',
];

export const wildlifeImages = [
    'src/assets/images/gallery/wildlife/wildlife_01.jpg',
    'src/assets/images/gallery/wildlife/wildlife_02.jpg',
    'src/assets/images/gallery/wildlife/wildlife_03.jpg',
    'src/assets/images/gallery/wildlife/wildlife_04.jpg',
    'src/assets/images/gallery/wildlife/wildlife_05.jpg',
    'src/assets/images/gallery/wildlife/wildlife_06.jpg',
    'src/assets/images/gallery/wildlife/wildlife_07.jpg',
    'src/assets/images/gallery/wildlife/wildlife_08.jpg',
    'src/assets/images/gallery/wildlife/wildlife_09.jpg',
    'src/assets/images/gallery/wildlife/wildlife_10.jpg',
    'src/assets/images/gallery/wildlife/wildlife_11.jpg',
    'src/assets/images/gallery/wildlife/wildlife_12.jpg',
    'src/assets/images/gallery/wildlife/wildlife_13.jpg',
    'src/assets/images/gallery/wildlife/wildlife_14.jpg',
    'src/assets/images/gallery/wildlife/wildlife_15.jpg',
    'src/assets/images/gallery/wildlife/wildlife_16.jpg',
];

export const articImages = [
    'src/assets/images/gallery/artic/artic_01.jpg',
    'src/assets/images/gallery/artic/artic_02.jpg',
    'src/assets/images/gallery/artic/artic_03.jpg',
    'src/assets/images/gallery/artic/artic_04.jpg',
    'src/assets/images/gallery/artic/artic_05.jpg',
    'src/assets/images/gallery/artic/artic_06.jpg',
    'src/assets/images/gallery/artic/artic_07.jpg',
    'src/assets/images/gallery/artic/artic_08.jpg',
    'src/assets/images/gallery/artic/artic_09.jpg',
    'src/assets/images/gallery/artic/artic_10.jpg',
    'src/assets/images/gallery/artic/artic_11.jpg',
    'src/assets/images/gallery/artic/artic_12.jpg',
    'src/assets/images/gallery/artic/artic_13.jpg',
    'src/assets/images/gallery/artic/artic_14.jpg',
    'src/assets/images/gallery/artic/artic_15.jpg',
    'src/assets/images/gallery/artic/artic_16.jpg',
];

export const bnwImages = [
    'src/assets/images/gallery/black&white/b&w_01.jpg',
    'src/assets/images/gallery/black&white/b&w_02.jpg',
    'src/assets/images/gallery/black&white/b&w_03.jpg',
    'src/assets/images/gallery/black&white/b&w_04.jpg',
    'src/assets/images/gallery/black&white/b&w_05.jpg',
    'src/assets/images/gallery/black&white/b&w_06.jpg',
    'src/assets/images/gallery/black&white/b&w_07.jpg',
    'src/assets/images/gallery/black&white/b&w_08.jpg',
    'src/assets/images/gallery/black&white/b&w_09.jpg',
    'src/assets/images/gallery/black&white/b&w_10.jpg',
    'src/assets/images/gallery/black&white/b&w_11.jpg',
    'src/assets/images/gallery/black&white/b&w_12.jpg',
    'src/assets/images/gallery/black&white/b&w_13.jpg',
    'src/assets/images/gallery/black&white/b&w_14.jpg',
    'src/assets/images/gallery/black&white/b&w_15.jpg',
    'src/assets/images/gallery/black&white/b&w_16.jpg',
];